version: '3.8'
services:
  hooks:
    build: .
    ports:
      - "8000:8000"
    environment:
      # When using compose networking initialize data with service name of the consumer instead of default localhost
      - DATA=sample-data-docker
  consumer:
    build: ./consumer
    ports:
      - "8888:8888"
